package org.vmgs.com.ManagedBeans;

import java.io.Serializable;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.vmgs.com.clases.Persona;

@ManagedBean
@SessionScoped
public class FormularioBean implements Serializable {

	/*-----------Members  ------------------------*/
	private static final long serialVersionUID = 1L;
	private Persona persona;
	// Generated by Map , int es primitivo por eso uso Integer que es el wrapper
	private static Map<String, Integer> MapTecnologies;
	//combo source
	private static Map<String, Integer> MapFoot;
	private List<Persona> personaLista;
	/*-----------Members  ------------------------*/

	public FormularioBean() {
		persona = new Persona();
		this.personaLista = new ArrayList<Persona>();
		persona.setRespuesta("Mi esposa");
	}

	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}

	/**
	 * @param persona
	 *            the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	static {
		MapTecnologies = new HashMap<String, Integer>();// label, value
		MapTecnologies.put("Phyton", 1);
		MapTecnologies.put("C#", 2);
		MapTecnologies.put("SQL", 3);
		MapTecnologies.put("JavaScript", 4);
		MapTecnologies.put("VB.NET", 5);
		
		MapFoot = new TreeMap<String, Integer>();// label, value
		MapFoot.put("Sopa", 1);
		MapFoot.put("Ensalada", 2);
		MapFoot.put("Pescado", 3);
			
	}

	/**
	 * @return the mapTecnologies
	 */
	public Map<String, Integer> getMapTecnologies() {
		return MapTecnologies;
	}
	
	public Map<String, Integer> getMapFoot() {
		return this.MapFoot;
	}
	
	public List<Persona> getPersonaLista(){
		return this.personaLista;
	}
	
	public void setPersonaLista(List<Persona> personas){
		this.personaLista=personas;
	}

	public String GuardarPersona() {
		System.out.print(persona.toString());
		this.personaLista.add(persona);
		persona = new Persona();// limpia el formulario
		return "";
	}
	
	
	public String deleteAction(){
		FacesContext fc = FacesContext.getCurrentInstance();
		Map<String,String> params = fc.getExternalContext().getRequestParameterMap();
		String parametro = params.get("personaId");
		System.out.print(parametro);
		Persona toDelete;
		if(parametro != ""){
			for(Persona p : personaLista){
				if(p.getPrimerNombre() != null && p.getPrimerNombre().contains(parametro))
				personaLista.remove(p);
				System.out.print("Se elimino: "+ p.getPrimerNombre() );
				break;
			}
		}
		return null;
	}
}
