package org.vmgs.com.ManagedBeans;

import java.io.Serializable;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import org.vmgs.com.clases.Persona;
import javax.faces.event.ActionEvent;

@ManagedBean
@SessionScoped
public class FormularioBean implements Serializable {

	/*-----------Members  ------------------------*/
	private static final long serialVersionUID = 1L;
	private Persona persona;
	// Generated by Map , int es primitivo por eso uso Integer que es el wrapper
	private static Map<String, Integer> MapTecnologies;
	//combo source
	private static Map<String, Integer> MapFoot;
	private List<Persona> personaLista;
	private String currentTheme ;
	private static Map<String,String> themes;
	/*-----------Members  ------------------------*/

	public FormularioBean() {
		persona = new Persona();
		this.personaLista = new ArrayList<Persona>();
		persona.setRespuesta("Mi esposa");
	}

	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}

	/**
	 * @param persona
	 *            the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	public String getCurrentTheme(){
		return (this.currentTheme == null || this.currentTheme.equals("")) ? "aristo" : this.currentTheme;
	}
	
	public void setCurrentTheme(String value){
		this.currentTheme= value;
	}

	static {
		MapTecnologies = new HashMap<String, Integer>();// label, value
		MapTecnologies.put("Phyton", 1);
		MapTecnologies.put("C#", 2);
		MapTecnologies.put("SQL", 3);
		MapTecnologies.put("JavaScript", 4);
		MapTecnologies.put("VB.NET", 5);
		
		MapFoot = new TreeMap<String, Integer>();// label, value
		MapFoot.put("Sopa", 1);
		MapFoot.put("Ensalada", 2);
		MapFoot.put("Pescado", 3);
		 
		themes = new TreeMap<String,String>();
		themes.put("Aristo", "aristo");  
        themes.put("Black-Tie", "black-tie");  
        themes.put("Blitzer", "blitzer");  
        themes.put("Bluesky", "bluesky");  
        themes.put("Casablanca", "casablanca");  
        themes.put("Cupertino", "cupertino");  
        themes.put("Dark-Hive", "dark-hive");  
        themes.put("Dot-Luv", "dot-luv");  
        themes.put("Eggplant", "eggplant");  
        themes.put("Excite-Bike", "excite-bike");  
        themes.put("Flick", "flick");  
        themes.put("Glass-X", "glass-x");  
        themes.put("Hot-Sneaks", "hot-sneaks");  
        themes.put("Humanity", "humanity");  
        themes.put("Le-Frog", "le-frog");  
        themes.put("Midnight", "midnight");  
        themes.put("Mint-Choc", "mint-choc");  
        themes.put("Overcast", "overcast");  
        themes.put("Pepper-Grinder", "pepper-grinder");  
        themes.put("Redmond", "redmond");  
        themes.put("Rocket", "rocket");  
        themes.put("Sam", "sam");  
        themes.put("Smoothness", "smoothness");  
        themes.put("South-Street", "south-street");  
        themes.put("Start", "start");  
        themes.put("Sunny", "sunny");  
        themes.put("Swanky-Purse", "swanky-purse");  
        themes.put("Trontastic", "trontastic");  
        themes.put("UI-Darkness", "ui-darkness");  
        themes.put("UI-Lightness", "ui-lightness");  
        themes.put("Vader", "vader");  
			
	}

	/**
	 * @return the mapTecnologies
	 */
	public Map<String, Integer> getMapTecnologies() {
		return MapTecnologies;
	}
	
	public Map<String, Integer> getMapFoot() {
		return this.MapFoot;
	}
	
	public Map<String,String> getThemes(){
		return this.themes;
	}
	
	public List<Persona> getPersonaLista(){
		return this.personaLista;
	}
	
	public void setPersonaLista(List<Persona> personas){
		this.personaLista=personas;
	}

	public String GuardarPersona() {
		System.out.print(persona.getPrimerNombre());
		this.personaLista.add(persona);
		persona = new Persona();// limpia el formulario
		return "formularios?faces-redirect=true";
	}
	
	public String GuardarPersonaFromPrime() {
		System.out.print(persona.getPrimerNombre());
		this.personaLista.add(persona);
		persona = new Persona();// limpia el formulario
		return "primeForm?faces-redirect=true";
		
	}
	
	public void testButtonActionListener(ActionEvent event) {
        System.out.println("testButtonActionListener invoked");
    }
	
	public String deleteAction(){
		FacesContext fc = FacesContext.getCurrentInstance();
		Map<String,String> params = fc.getExternalContext().getRequestParameterMap();
		String parametro = params.get("personaId");
		System.out.print("\n " + parametro);
		Persona toDelete;
		if(parametro != ""){
			for(Persona p : personaLista){
				if(p.getPrimerNombre() != null && p.getPrimerNombre().contains(parametro)){
					personaLista.remove(p);
					System.out.print("\n Se elimino: "+ p.toString() );
					break;
				}
			}
		}
		return null;
		
	}

	//marcar el objeto como editable
	public String editAction(Persona p){
		p.setEditable(true);
		return null;
	}
	
	public String GuardarCambios(){
		//get all existing value but set "editable" to false 
		for (Persona p : personaLista){
			p.setEditable(false);
		}
		//return to current page
		return null;

	}
	
	public void favoriteFootvalueChangeMethod(ValueChangeEvent e){
		  e.getComponent().processUpdates(FacesContext.getCurrentInstance()); //estas dos lineas para
		  FacesContext.getCurrentInstance().renderResponse();//que no dispare la validacion de jsf y tambien immediate="true" aya en el control
		System.out.print("Comida Favorita cambio: " + e.getNewValue().toString());
	}
}
