package org.vmgs.com.ManagedBeans;

import java.io.Serializable;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.vmgs.com.clases.Persona;

@ManagedBean
@SessionScoped
public class FormularioBean implements Serializable {

	/*-----------Members  ------------------------*/
	private static final long serialVersionUID = 1L;
	private Persona persona;
	// Generated by Map , int es primitivo por eso uso Integer que es el wrapper
	private static Map<String, Integer> MapTecnologies;

	/*-----------Members  ------------------------*/

	public FormularioBean() {
		persona = new Persona();
		persona.setRespuesta("Mi esposa");
	}

	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}

	/**
	 * @param persona
	 *            the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	static {
		MapTecnologies = new HashMap<String, Integer>();// label, value
		MapTecnologies.put("Java", 1);
		MapTecnologies.put("C#", 2);
		MapTecnologies.put("SQL", 3);
		MapTecnologies.put("JavaScript", 4);
		MapTecnologies.put("VB.NET", 5);
	}

	/**
	 * @return the mapTecnologies
	 */
	public Map<String, Integer> getMapTecnologies() {
		return MapTecnologies;
	}

	public String GuardarPersona() {
		System.out.print(persona.toString());

		persona = new Persona();// limpia el formulario
		return "";
	}
}
